[package]
name = "portools"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
chrono = { version = "0.4.24", features = ["serde"] }
csv = "1.2.1"
futures-util = "0.3.27"
rust_decimal = {version="1.29.1", features = ["serde"] }
rusty-money = { version ="0.4.1", features = ["iso"] }
serde = { version = "1.0.158", features = ["derive"] }
uuid = { version = "1.3.0", features = [
    "v4",                # Lets you generate random UUIDs
    "fast-rng",          # Use a faster (but still sufficiently random) RNG
    "macro-diagnostics", # Enable better diagnostics for compile-time UUIDs
    "serde"
]}